import palette from "./palette";

const typography = {
	h1: {
		color: palette.text.primary,
		fontWeight: 500,
		fontSize: "35px",
		letterSpacing: "-0.24px",
		lineHeight: "40px",
		fontFamily: "GoldleafBoldPersonal",
	},
	h2: {
		color: palette.text.primary,
		fontWeight: 500,
		fontSize: "29px",
		letterSpacing: "-0.24px",
		lineHeight: "32px",
		fontFamily: "GoldleafBoldPersonal",
	},
	h3: {
		color: palette.text.primary,
		fontWeight: 500,
		fontSize: "24px",
		letterSpacing: "-0.06px",
		lineHeight: "28px",
		fontFamily: "GoldleafBoldPersonal",
	},
	h4: {
		color: palette.text.primary,
		fontWeight: 500,
		fontSize: "18px",
		letterSpacing: "-0.06px",
		lineHeight: "24px",
		fontFamily: "GoldleafBoldPersonal",
	},
	h5: {
		color: palette.text.primary,
		fontWeight: 500,
		fontSize: "16px",
		letterSpacing: "-0.05px",
		lineHeight: "20px",
		fontFamily: "GoldleafBoldPersonal",
	},
	h6: {
		color: palette.text.primary,
		fontWeight: 500,
		fontSize: "14px",
		letterSpacing: "-0.05px",
		lineHeight: "20px",
		fontFamily: "GoldleafBoldPersonal",
	},
	subtitle1: {
		color: palette.text.primary,
		fontSize: "16px",
		letterSpacing: "-0.05px",
		lineHeight: "25px",
		fontFamily: "GoldleafBoldPersonal",
	},
	subtitle2: {
		color: palette.text.secondary,
		fontWeight: 400,
		fontSize: "14px",
		letterSpacing: "-0.05px",
		lineHeight: "21px",
		fontFamily: "GoldleafBoldPersonal",
	},
	body1: {
		color: palette.text.primary,
		fontSize: "14px",
		letterSpacing: "-0.05px",
		lineHeight: "21px",
		fontFamily: "GoldleafBoldPersonal",
	},
	body2: {
		color: palette.text.secondary,
		fontSize: "12px",
		letterSpacing: "-0.04px",
		lineHeight: "18px",
		fontFamily: "GoldleafBoldPersonal",
	},
	button: {
		color: palette.text.primary,
		fontSize: "14px",
		fontFamily: "GoldleafBoldPersonal",
	},
	caption: {
		color: palette.text.secondary,
		fontSize: "11px",
		letterSpacing: "0.33px",
		lineHeight: "13px",
		fontFamily: "GoldleafBoldPersonal",
	},
	overline: {
		color: palette.text.secondary,
		fontSize: "11px",
		fontWeight: 500,
		letterSpacing: "0.33px",
		lineHeight: "13px",
		textTransform: "uppercase",
		fontFamily: "GoldleafBoldPersonal",
	},
};

export default typography;
